export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const COUNTRIES_REQUEST = "COUNTRIES_REQUEST";
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAIL = "COUNTRIES_FAIL";

export const STEPPER_INCREMENT = "STEPPER_INCREMENT";
export const STEPPER_DECREMENT = "STEPPER_DECREMENT";
